databases:
  - name: amarjomi
    databaseName: amarjomi
    user: amarjomi
    plan: free

services:
  - type: web
    name: amarjomi
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: amarjomi
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
